### ISSUE TITLE
TX **** is not in the chain, after 120 seconds

### ISSUE THREAD

**Issue by Thatsmejh** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#20]
Often i'm getting a TimeOut issue, cant figure out what it could be. Checked the tx hash, and its indeed not in BSCS

Do you hava a clue or is this just back luck? 

`Amount for Buy: 0.03 BNB
Token to Interact : 0x817aea85fa208f499f08276a4340e4e35d50b643
Transaction to send: 1
Amount per transaction : 0.03000000
Await Blocks before buy : 0
Take Profit Percent : 50
Target Output for Take Profit: 0.04500000
---------------------------------
[DONE] Liquidity is Added!
Checking Token is Honeypot...
[DONE] Token is NOT a Honeypot!
🚀  await Buy
BUY Hash: 0xdd4ad458434be4885f3130ffcaab3d7e07e24f0ed390400e1abe97b61ab67c12
🚀  await BuyTraceback (most recent call last):
  File "web3\eth.py", line 674, in wait_for_transaction_receipt
🌙  await Buy  File "web3\_utils\transactions.py", line 144, in wait_for_transaction_receipt
  File "web3\_utils\threads.py", line 89, in sleep
  File "web3\_utils\threads.py", line 82, in check
web3._utils.threads.Timeout: 120 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Sniper.py", line 253, in <module>
  File "Sniper.py", line 244, in StartUP
  File "Sniper.py", line 117, in awaitBuy
  File "txns.py", line 106, in buy_token
  File "web3\_utils\decorators.py", line 51, in wrapper
  File "web3\eth.py", line 668, in waitForTransactionReceipt
  File "web3\eth.py", line 676, in wait_for_transaction_receipt
web3.exceptions.TimeExhausted: Transaction HexBytes('0xdd4ad458434be4885f3130ffcaab3d7e07e24f0ed390400e1abe97b61ab67c12') is not in the chain, after 120 seconds
[27216] Failed to execute script 'Sniper' due to unhandled exception!`

**Comment by Trading-Tiger** [comment]
Hi,
Yes, the problem is since a few days, this is due to the public RPC, try to get your own RPC access, maybe https://www.quicknode.com/chains/bsc or Free alternatives.
