### ISSUE TITLE
sell error

### ISSUE THREAD

**Issue by internalsync** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#25]
I sell I my token to remind you of the error。
I'm using the latest version

```
Traceback (most recent call last):
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/Sniper.py", line 264, in <module>
    SniperBot().StartUP()
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/Sniper.py", line 219, in StartUP
    print(self.TXN.sell_tokens()[1])
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/txns.py", line 173, in sell_tokens
    txn.update({ 'gas' : int(self.estimateGas(txn))})
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/txns.py", line 78, in estimateGas
    gas = self.w3.eth.estimateGas({
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 576, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: TransferHelper: TRANSFER_FROM_FAILED
```

**Comment by Trading-Tiger** [comment]
Honeypot? Please share your token address next time so we can look further!
This error can't come from our contract, because we don't use TransferHelper since V1.6.

Have you ever checked your token manual in the API? e.g. https://ishoneypot.trading-tigers.com/token/0x34faa80fec0233e045ed4737cc152a71e490e2e3

**Comment by leoynick** [comment]
I have had the same problem with this token 0xf8ae4ef55628aacfb9bd6e777b0f5d35c173f624. But in pacakeswap I have been able to sell it

**Comment by Trading-Tiger** [comment]
https://ishoneypot.trading-tigers.com/token/0xf8ae4ef55628aacfb9bd6e777b0f5d35c173f624
Funny, this token is detected as a honeypot.

**Comment by internalsync** [comment]
https://ishoneypot.trading-tigers.com/token/0x141df21e93460216Fe0692e756927118CE4c65BE  is not honeypot.
sell log：

```
Traceback (most recent call last):
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/Sniper.py", line 264, in <module>
    SniperBot().StartUP()
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/Sniper.py", line 219, in StartUP
    print(self.TXN.sell_tokens()[1])
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/txns.py", line 173, in sell_tokens
    txn.update({ 'gas' : int(self.estimateGas(txn))})
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/txns.py", line 78, in estimateGas
    gas = self.w3.eth.estimateGas({
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 576, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: TransferHelper: TRANSFER_FROM_FAILED
```
