### ISSUE TITLE
sell error

### ISSUE THREAD

**Issue by internalsync** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#27]
token: 0x141df21e93460216Fe0692e756927118CE4c65BE
error logs:

```
Traceback (most recent call last):
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/Sniper.py", line 264, in <module>
    SniperBot().StartUP()
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/Sniper.py", line 219, in StartUP
    print(self.TXN.sell_tokens()[1])
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/txns.py", line 173, in sell_tokens
    txn.update({ 'gas' : int(self.estimateGas(txn))})
  File "/data/Pancakeswap_BSC_Sniper_Bot_v2/txns.py", line 78, in estimateGas
    gas = self.w3.eth.estimateGas({
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/eth.py", line 759, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
  File "/root/.pyenv/versions/py_3.9.9_pancakeswap_bsc_sniper/lib/python3.9/site-packages/web3/_utils/method_formatters.py", line 576, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: TransferHelper: TRANSFER_FROM_FAILED
```

**Comment by glorindelf** [comment]
Hi, I had the same problem with tokens:
0xbd7b45e4a8e7042b458a8ff08f29aa8eae43f269
0x000000ef379ee7f4c051f4b9af901a9219d9ec5c (this one is detected as honeypot, but I was able to sell it manually via pancakeswap)

**Comment by sam007hero** [comment]
excellent job guys.. but it would be amazing if you add telegram scraper.. scrape and notice the contract address from the telegram account what we chose and buy automatically.. thank you

**Comment by Trading-Tiger** [comment]
Thanks, Thanks!
Hopefully no Errors likes this in v2.0 and up!
Have fun guys and much success!

**Comment by Trading-Tiger** [comment]
Are there still problems with token sales here?
