### ISSUE TITLE
[ERROR] i have received this exception error

### ISSUE THREAD

**Issue by sparkmobi** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#29]
i have received this error but the buying order execution happened

`await BuyTraceback (most recent call last):
  File "web3\eth.py", line 674, in wait_for_transaction_receipt
  File "web3\_utils\transactions.py", line 144, in wait_for_transaction_receipt
  File "web3\_utils\threads.py", line 89, in sleep
  File "web3\_utils\threads.py", line 82, in check
web3._utils.threads.Timeout: 120 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Sniper.py", line 264, in <module>
  File "Sniper.py", line 255, in StartUP
  File "Sniper.py", line 111, in awaitBuy
  File "txns.py", line 123, in buy_token
  File "web3\_utils\decorators.py", line 51, in wrapper
  File "web3\eth.py", line 668, in waitForTransactionReceipt
  File "web3\eth.py", line 676, in wait_for_transaction_receipt
web3.exceptions.TimeExhausted: Transaction HexBytes('0xfc30bc687706383290fd3207f4499b572dbf58bexxxxxxxxxxxxxxxx') is not in the chain, after 120 seconds
[3288] Failed to execute script 'Sniper' due to unhandled exception!`

**Comment by Trading-Tiger** [comment]
Hi,
Please take a look @ https://github.com/Trading-Tiger/Pancakeswap_BSC_Sniper_Bot/issues/20
