### ISSUE TITLE
binascii.Error: Non-hexadecimal digit found

### ISSUE THREAD

**Issue by kerimgker** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#30]
[DONE] Liquidity is Added!
Checking Token is Honeypot...
[DONE] Token is NOT a Honeypot!
🌕  await BuyTraceback (most recent call last):
  File "Sniper.py", line 264, in <module>
  File "Sniper.py", line 255, in StartUP
  File "Sniper.py", line 111, in awaitBuy
  File "txns.py", line 117, in buy_token
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 727, in sign_transaction
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 250, in from_key
  File "eth_utils\decorators.py", line 18, in _wrapper
  File "eth_account\account.py", line 774, in _parsePrivateKey
  File "hexbytes\main.py", line 23, in __new__
  File "hexbytes\_utils.py", line 17, in to_bytes
  File "hexbytes\_utils.py", line 50, in hexstr_to_bytes
binascii.Error: Non-hexadecimal digit found
[16220] Failed to execute script 'Sniper' due to unhandled exception!

Hey mate, how can I solve this problem, thank you.

**Comment by Trading-Tiger** [comment]
Hi,
We currently do not support seed words.
This error comes from a wrong Secret Key. ( Settings.json => line3 => "metamask_private_key": "HERE YOUR SECRET KEY" ,   )

If you do not have a secret key, use Metamask, import your seed words and export your secret key.
