### ISSUE TITLE
web3.exceptions.ContractLogicError: execution reverted: Wrapped forbiden

### ISSUE THREAD

**Issue by razor778** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#47]
Hi, I have installed the python version on a VPS with Windows server 2019, I have setup the private KEY and the address to buy, but when I run a command I get the following error:

`---------------------------------
Amount for Buy: 0.001 BNB
Token to Interact : 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c
Transaction to send: 1
Amount per transaction : 0.00100000
Await Blocks before buy : 0
---------------------------------
Start BuyOnly, buy now with {self.amountForSnipe}BNB tokens!
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\Pancakeswap_BSC_Sniper_Bot-main\Sniper.py", line 286, in <module>
    SniperBot().StartUP()
  File "C:\Users\Administrator\Desktop\Pancakeswap_BSC_Sniper_Bot-main\Sniper.py", line 249, in StartUP
    print(self.TXN.buy_token()[1])
  File "C:\Users\Administrator\Desktop\Pancakeswap_BSC_Sniper_Bot-main\txns.py", line 146, in buy_token
    txn.update({ 'gas' : int(self.estimateGas(txn))})
  File "C:\Users\Administrator\Desktop\Pancakeswap_BSC_Sniper_Bot-main\txns.py", line 94, in estimateGas
    gas = self.w3.eth.estimateGas({
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\eth.py", line 855, in estimate_gas
    return self._estimate_gas(transaction, block_identifier)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\module.py", line 57, in caller
    result = w3.manager.request_blocking(method_str,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\manager.py", line 198, in request_blocking
    return self.formatted_response(response,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\manager.py", line 170, in formatted_response
    apply_error_formatters(error_formatters, response)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\manager.py", line 70, in apply_error_formatters
    formatted_resp = pipe(response, error_formatters)
  File "cytoolz/functoolz.pyx", line 667, in cytoolz.functoolz.pipe
    return c_pipe(data, funcs)
  File "cytoolz/functoolz.pyx", line 642, in cytoolz.functoolz.c_pipe
    data = func(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\web3\_utils\method_formatters.py", line 576, in raise_solidity_error_on_revert
    raise ContractLogicError(response['error']['message'])
web3.exceptions.ContractLogicError: execution reverted: Wrapped forbiden`

I tried to change any setting but absolutely nothing happens, I tried with different token addresses but always the same problem, I tried to use moralis as rpc but nothing.

I run the command via cmd in the following way:

`C: \ Users \ Administrator \ Desktop \ Pancakeswap_BSC_Sniper_Bot-main> py Sniper.py -t 0xbb4CdB9CBd36B01bD1cBaEBF2De08d9173bc095c -a 0.001 --buyonly`

I have tried all available commands but nothing.

I noticed that this problem was mentioned in previous issue requests:

https://github.com/Trading-Tiger/Pancakeswap_BSC_Sniper_Bot/issues/27

but in my case it has persisted for several hours

Any solutions ?

**Comment by Trading-Tiger** [comment]
You cannot trade WBNB with Our Contract look at "execution reverted: Wrapped forbiden".
We have forbidden Wrapped BNB because we always look for the largest pool and this leads to an unnecessary swap at WBNB.
Try BUSD for example.
