### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character

### ISSUE THREAD

**Issue by rlsblogse** [Trading-Tiger/Pancakeswap_BSC_Sniper_Bot#52]
hello,
what i did wrong? 
this  is that command i run
python3 Sniper.py -t 0x740e08e52542df19d7f2f9cbf3924ac0bfe53071 -a 0.001 -tp 3

and output is below.

[DONE] TradingTigers Sniper Bot finish!

  ______               ___
 /_  __/________ _____/ (_)___  ____ _
  / / / ___/ __ `/ __  / / __ \/ __ `/
 / / / /  / /_/ / /_/ / / / / / /_/ /
/_/_/_/__ \__,_/\__,_/_/_/ /_/\__, /
 /_  __(_)___ ____  _________/____/
  / / / / __ `/ _ \/ ___/ ___/
 / / / / /_/ /  __/ /  (__  )
/_/ /_/\__, /\___/_/  /____/
      /____/

Attention, You pay a 0.77% Tax on your swap amount!
Start Sniper Tool with following arguments:
---------------------------------
Amount for Buy: 0.001 BNB
Token to Interact : 0x740e08e52542df19d7f2f9cbf3924ac0bfe53071
Transaction to send: 1
Amount per transaction : 0.00100000
Await Blocks before buy : 0
Take Profit Percent : 3
---------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/halo/halo.py", line 410, in _render_frame
    self._write(output)
  File "/usr/local/lib/python3.6/dist-packages/halo/halo.py", line 305, in _write
    self._stream.write(s)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u280b' in position 10: ordinal not in range(256)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Sniper.py", line 346, in <module>
    SniperBot().StartUP()
  File "Sniper.py", line 304, in StartUP
    self.awaitLiquidity()
  File "Sniper.py", line 192, in awaitLiquidity
    spinner.start()
  File "/usr/local/lib/python3.6/dist-packages/halo/halo.py", line 498, in start
    self._render_frame()
  File "/usr/local/lib/python3.6/dist-packages/halo/halo.py", line 412, in _render_frame
    self._write(encode_utf_8_text(output))
  File "/usr/local/lib/python3.6/dist-packages/halo/halo.py", line 305, in _write
    self._stream.write(s)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 41, in write
    self.__convertor.write(text)
  File "/usr/local/lib/python3.6/dist-packages/colorama/ansitowin32.py", line 164, in write
    self.wrapped.write(text)
TypeError: write() argument must be str, not bytes

----

btw  those 2 commands works
python3 Sniper.py -t 0x740e08e52542df19d7f2f9cbf3924ac0bfe53071 -a 0.001 --buyonly
python3 Sniper.py -t 0x740e08e52542df19d7f2f9cbf3924ac0bfe53071 -a 0.003 --sellonly

but those for manual.

i want automatic like pending order .

regards

**Comment by Trading-Tiger** [comment]
This looks like you are having problems with halo spinner, try installing halo again.
"python -m pip install halo -U"
or your operating system does not support "Unicode latin-1" characterset.
